version: "3"
services:
  torch:
    image: flantick/segmenter
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]