version: "3"
services:
  torch:
    image: flantick/neuralnettrainer
    ports:
      - 8888:8888
    volumes:
      - source:target
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]